export {
  buildChapterRenderData,
  canSkipReaderRestore,
  clampProgress,
  createRestoreTargetFromNavigationIntent,
  createRestoreTargetFromPersistedState,
  getChapterLocalProgress,
  getChapterScrollableRange,
  getContainerProgress,
  getPageIndexFromProgress,
  getScrollTopForChapterProgress,
  hasReaderRestoreTarget,
  resolvePagedRestoreTargetPageIndex,
  resolvePagedTargetPage,
  SCROLL_READING_ANCHOR_RATIO,
  shouldKeepReaderRestoreMask,
  type ChapterRenderData,
} from '@shared/utils/readerPosition';
