export { default as ReaderFlowBlock } from '../components/reader/ReaderFlowBlock';
export {
  calculateVisibleScrollBlockRanges,
  resolveCurrentPagedLocator,
  resolveCurrentScrollLocator,
  resolveCurrentScrollLocatorOffset,
  resolvePagedViewportState,
} from '../reader-layout';
export {
  buildStaticPagedChapterTree,
  buildStaticScrollChapterTree,
  buildStaticSummaryShellTree,
  composePaginatedChapterLayout,
  createChapterContentHash,
  createReaderLayoutSignature,
  createReaderTypographyMetrics,
  createReaderViewportMetrics,
  createScrollImageLayoutConstraints,
  estimateReaderRenderQueryManifest,
  findLocatorForLayoutOffset,
  findPageIndexForLocator,
  findPageIndexForLocatorInStaticTree,
  findVisibleBlockRange,
  findVisibleBlockRangeFromBlockSummaries,
  getChapterBoundaryLocator,
  getChapterEndLocator,
  getChapterStartLocator,
  getOffsetForLocator,
  getOffsetForLocatorInStaticTree,
  getPagedContentHeight,
  getPageStartLocator,
  getPageStartLocatorFromStaticTree,
  measurePagedReaderChapterLayout,
  measureReaderChapterLayout,
  measureScrollReaderChapterLayout,
  CHAPTER_TITLE_PARAGRAPH_INDEX,
  PAGED_VIEWPORT_TOP_PADDING_PX,
  serializeReaderLayoutSignature,
} from '../utils/layout/readerLayout';
export type {
  MeasuredChapterLayout,
  PageSlice,
  PaginatedChapterLayout,
  ReaderBlankPageItem,
  ReaderBlock,
  ReaderImageLayoutConstraints,
  ReaderImagePageItem,
  ReaderLayoutSignature,
  ReaderLineRange,
  ReaderLocator,
  ReaderMeasuredLine,
  ReaderPageColumn,
  ReaderPageItem,
  ReaderRenderQueryManifest,
  ReaderRenderVariant,
  ReaderTextLayoutEngine,
  ReaderTextPageItem,
  ReaderTypographyMetrics,
  ReaderViewportMetrics,
  StaticChapterRenderTree,
  StaticPagedChapterTree,
  StaticPagedNode,
  StaticReaderNode,
  StaticScrollBlockNode,
  StaticScrollChapterTree,
  StaticSummaryShellTree,
  StaticTextLine,
  StaticTextLineRange,
  VirtualBlockMetrics,
  VisibleBlockRange,
} from '../utils/layout/readerLayout';
export {
  getReaderContentBlockClassName,
  resolveReaderContentRootProps,
} from '../utils/layout/readerContentStyling';
export type { ReaderContentRootProps, ReaderContentRootTheme } from '../utils/layout/readerContentStyling';
export {
  createReaderImageEntryId,
  sortReaderImageGalleryEntries,
} from '@shared/reader-rendering';
export type { ReaderImageActivationPayload, ReaderImageGalleryEntry } from '@shared/contracts/reader';
export { preloadReaderImageResources } from '@domains/reader-media';
export {
  buildNovelFlowIndex,
  createChapterFlowManifestFromRenderCacheRecord,
  createChapterFlowManifestFromScrollTree,
  isChapterFlowManifestCompatible,
  mergeChapterFlowManifests,
  resolveGlobalOffsetPosition,
  resolveGlobalPagePosition,
  resolveLocatorGlobalOffset,
  resolveLocatorGlobalPageIndex,
  toGlobalOffset,
  toGlobalPageIndex,
} from '../utils/flow-index/novelFlowIndex';
export type {
  ChapterFlowBlockSummary,
  ChapterFlowManifest,
  ChapterFlowManifestIdentity,
  ChapterFlowManifestStatus,
  GlobalPagedPosition,
  GlobalScrollPosition,
  NovelFlowChapterEntry,
  NovelFlowIndex,
} from '../utils/flow-index/novelFlowIndex';
