export { default as ReaderFlowBlock } from '../components/reader/ReaderFlowBlock';
export {
  calculateVisibleScrollBlockRanges,
  resolveCurrentPagedLocator,
  resolveCurrentScrollLocator,
  resolveCurrentScrollLocatorOffset,
  resolvePagedViewportState,
} from '../reader-layout';
export {
  buildStaticPagedChapterTree,
  buildStaticScrollChapterTree,
  buildStaticSummaryShellTree,
  composePaginatedChapterLayout,
  createChapterContentHash,
  createReaderLayoutSignature,
  createReaderTypographyMetrics,
  createReaderViewportMetrics,
  createScrollImageLayoutConstraints,
  estimateReaderRenderQueryManifest,
  findLocatorForLayoutOffset,
  findPageIndexForLocator,
  findPageIndexForLocatorInStaticTree,
  findVisibleBlockRange,
  getChapterBoundaryLocator,
  getChapterEndLocator,
  getChapterStartLocator,
  getOffsetForLocator,
  getOffsetForLocatorInStaticTree,
  getPagedContentHeight,
  getPageStartLocator,
  getPageStartLocatorFromStaticTree,
  measurePagedReaderChapterLayout,
  measureReaderChapterLayout,
  measureScrollReaderChapterLayout,
  PAGED_VIEWPORT_TOP_PADDING_PX,
  serializeReaderLayoutSignature,
} from '../utils/readerLayout';
export type {
  MeasuredChapterLayout,
  PageSlice,
  PaginatedChapterLayout,
  ReaderBlankPageItem,
  ReaderBlock,
  ReaderImageLayoutConstraints,
  ReaderImagePageItem,
  ReaderLayoutSignature,
  ReaderLocator,
  ReaderMeasuredLine,
  ReaderPageColumn,
  ReaderPageItem,
  ReaderRenderQueryManifest,
  ReaderRenderVariant,
  ReaderTextLayoutEngine,
  ReaderTextPageItem,
  ReaderTypographyMetrics,
  ReaderViewportMetrics,
  StaticChapterRenderTree,
  StaticPagedChapterTree,
  StaticPagedNode,
  StaticReaderNode,
  StaticScrollBlockNode,
  StaticScrollChapterTree,
  StaticSummaryShellTree,
  StaticTextLine,
  VirtualBlockMetrics,
  VisibleBlockRange,
} from '../utils/readerLayout';
export {
  getReaderContentBlockClassName,
  resolveReaderContentRootProps,
} from '../utils/readerContentStyling';
export type { ReaderContentRootProps, ReaderContentRootTheme } from '../utils/readerContentStyling';
export {
  createReaderImageEntryId,
  sortReaderImageGalleryEntries,
} from '@shared/reader-content';
export type { ReaderImageActivationPayload, ReaderImageGalleryEntry } from '@shared/contracts/reader';
export { preloadReaderImageResources } from '@domains/reader-media';
