import { http, HttpResponse } from 'msw';

export const handlers = [
  http.get('/api/novels', () => HttpResponse.json([])),
  http.get('/api/novels/:id', () => HttpResponse.json({
    id: 1,
    title: 'Mock Novel',
    author: 'Mock Author',
    description: 'Mock description',
    tags: ['mock'],
    fileType: 'epub',
    hasCover: false,
    originalFilename: 'mock.epub',
    originalEncoding: 'utf-8',
    totalWords: 12345,
    chapter_count: 2,
    createdAt: '2026-03-18T00:00:00Z',
  })),
  http.get('/api/novels/:id/analysis/status', () => HttpResponse.json({
    job: {
      status: 'idle',
      currentStage: 'idle',
      analysisComplete: false,
      totalChapters: 2,
      analyzedChapters: 0,
      totalChunks: 1,
      completedChunks: 0,
      currentChunkIndex: 0,
      progressPercent: 0,
      pauseRequested: false,
      lastError: '',
      currentChunk: null,
      canStart: true,
      canPause: false,
      canResume: false,
      canRestart: false,
    },
    overview: null,
    chunks: [],
  })),
  http.get('/api/novels/:id/analysis/chapters/:chapterIndex', () => HttpResponse.json({ analysis: null })),
  http.get('/api/novels/:id/analysis/character-graph', () => HttpResponse.json({
    nodes: [
      {
        id: 'hero',
        name: 'Hero',
        role: 'Lead',
        description: 'Main character',
        weight: 90,
        sharePercent: 60,
        chapterCount: 2,
        chapters: [0, 1],
        isCore: true,
      },
      {
        id: 'ally',
        name: 'Ally',
        role: 'Support',
        description: 'Supporting character',
        weight: 40,
        sharePercent: 25,
        chapterCount: 2,
        chapters: [0, 1],
        isCore: false,
      },
    ],
    edges: [
      {
        id: 'hero-ally',
        source: 'hero',
        target: 'ally',
        type: '同伴',
        relationTags: ['同伴'],
        description: 'Work together',
        weight: 70,
        mentionCount: 4,
        chapterCount: 2,
        chapters: [0, 1],
      },
    ],
    meta: {
      totalChapters: 2,
      analyzedChapters: 2,
      nodeCount: 2,
      edgeCount: 1,
      hasOverview: true,
      hasData: true,
      isComplete: true,
      generatedAt: '2026-03-18T00:00:00Z',
    },
  })),
  http.get('/api/novels/:id/chapters', () => HttpResponse.json([
    { index: 0, title: 'Chapter 1', wordCount: 1200 },
    { index: 1, title: 'Chapter 2', wordCount: 980 },
  ])),
  http.get('/api/novels/:id/chapters/:idx', () => HttpResponse.json({
    index: 0,
    title: 'Chapter 1',
    content: 'content',
    wordCount: 1200,
    totalChapters: 2,
    hasPrev: false,
    hasNext: true,
  })),
  http.get('/api/novels/:id/reading-progress', () => HttpResponse.json({
    chapterIndex: 0,
    scrollPosition: 0,
    viewMode: 'original',
  })),
  http.put('/api/novels/:id/reading-progress', () => HttpResponse.json({ message: 'ok' })),
  http.get('/api/settings/ai-provider', () => HttpResponse.json({
    apiBaseUrl: '',
    modelName: '',
    contextSize: 32000,
    hasApiKey: false,
    maskedApiKey: '',
    updatedAt: null,
  })),
  http.get('/api/settings/purification-rules', () => HttpResponse.json([])),
  http.get('/api/settings/toc-rules', () => HttpResponse.json([])),
];
